build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    - phpcs-run
                    - js-scrutinizer-run
        tests: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'features/*'
checks:
    php: true
    javascript: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
